min_players:
  required: false
  type: integer

settings:
  required: false
  type: dict

maps:
  required: true
  type: list
  schema:
    type: dict
    schema:
      name:
        required: true
        type: string
      modes:
        required: true
        type: list
